apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Senha123"
        - name: MYSQL_DATABASE
          value: "meubanco"
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: init-volume
      volumes:
      - name: init-volume
        hostPath:
          path: /home/seu-usuario/caminho-completo/meuapp-k8s/database
